import { dealAssets } from "../assets/Deal/dealassets";
import { dealStatus } from "../assets/Deal/dealassets";
export const dealdata = [
  {
    id: 1,
    image: dealAssets[0],
    title: "Africa SME Funding Pool via Pezesha",
    desc: "Africa Multi-Sector Loans",
    est: "17% USDT",
    estdata: "28.69% with NEP",
    region: "Kenya",
    asset: "Revenue Based Financing",
    assetdesc: "Activate",
    status: dealStatus[0]
  },
  {
    id: 2,
    image: dealAssets[1],
    title: "Buy Now Pay Later Solutions for latin america",
    desc: "Consumers affordable & transparent installment loans for major purchases",
    est: "12% USDC",
    estdata: "28.69% with NEP",
    region: "Mexico",
    asset: "Buy Now Pay Later",
    assetdesc: "Repaid",
    status: dealStatus[1]
  },
  {
    id: 3,
    image: dealAssets[2],
    title: "Digital Super App Providing formal credit offerings",
    desc: "Provide formal credit offerings to the 20 million underbanked Egyptians",
    est: "22% BUSD",
    estdata: "28.69% with NEP",
    region: "Egypt",
    asset: "Unsecured Loans",
    assetdesc: "Full",
    status: dealStatus[2]
  },
  {
    id: 4,
    image: dealAssets[3],
    title: "full service MSME financial app",
    desc: "The first “buy before you sell” end-to-end financing solution for homeowners in Latin Amercia",
    est: "13.5% USDT",
    estdata: "28.69% with NEP",
    region: "Nigeria",
    asset: "Inventory Financing",
    assetdesc: "Open",
    status: dealStatus[0],
  },
  {
    id: 5,
    image: dealAssets[4],
    title: "Buy before you sell “financing solution for homeowners",
    desc: "Fully digital SME working capital lender that provides loans to Sounth Africa’s missing middle- businesses too large to access microfinance, or too small to secure large capital loans",
    est: "12% with NEP",
    estdata: "",
    region: "Mexico",
    asset: "Asset Backed Car and House Loans",
    assetdesc: "Full",
    status: dealStatus[2],
  },
  {
    id: 6,
    image: dealAssets[5],
    title: "Online SME working capital lender",
    desc: "Fully digital SME working capital lender that provides loans to Sounth Africa’s missing middle- businesses too large to access microfinance, or too small to secure large capital loans",
    est: "23.70% USDT",
    estdata: "28.69% with NEP",
    region: "South Africa",
    asset: "Invoices Advances",
    assetdesc: "Open",
    status: dealStatus[0],
  },
  {
    id: 7,
    image: dealAssets[6],
    title: "Online SME working capital lender",
    desc: "BizCapital is a digital lender for Brazilian SMEs that leverages alternative sources of data to underwrite its loans",
    est: "23.7% USDT",
    estdata: "28.69% with NEP",
    region: "Brazil",
    asset: "Invoice Advances ",
    assetdesc: "Repaid",
    status: dealStatus[1],
  },
  {
    id: 8,
    image: dealAssets[7],
    title: "Digital Payments based lender for mSMEs",
    desc: "Neogrowth pioneered unsecured  working capital loans for SMEs in India ",
    est: "21.4% USDT",
    estdata: "28.69% with NEP",
    region: "India",
    asset: "Invoice Advances",
    assetdesc: "Repaid",
    status: dealStatus[1],
  },
  {
    id: 9,
    image: dealAssets[8],
    title: "Secured lending platform for auto and home equity",
    desc: "Credits is a next-generation lending platform democratizing access to secured auto and home equity loans and payroll loans in Latin America.",
    est: "16% USDT",
    estdata: "28.69% with NEP",
    region: "Brazil",
    asset: "Asset Backed Car and House Loans",
    assetdesc: "Full",
    status: dealStatus[2],
  },
  {
    id: 10,
    image: dealAssets[9],
    title: "Licensed digital consumer lender offering low-cost loans",
    desc: "JULO is a digital consumer lender in Indonesia that leverages its propriety credit scoring method to offer affordable, short-term uncollateralized loans to new-to-credit and low-income consumers ",
    est: "13.9% USDT",
    estdata: "28.69% with NEP",
    region: "Indonesia",
    asset: "Cash Advances ",
    assetdesc: "Open",
    status: dealStatus[0],
  },
  {
    id: 11,
    image: dealAssets[10],
    title: "Embedded lending for SME importers in Latin America",
    desc: "Finkargo offers innovative and affordable cargo-collateralized credit solutions to SME importers across Latin America",
    est: "14% USDT",
    estdata: "28.69% with NEP",
    region: "Colombia",
    asset: "Cash Advances",
    assetdesc: "Open",
    status: dealStatus[0],
  },
];
